### ISSUE TITLE
Short fuzz runs sometimes corrupt state

### ISSUE THREAD

**Issue by zwbrbr** [Bristol-Braille/canute-ui#202]
Repeated one-second fuzz tests eventually result in:
```
Traceback (most recent call last):
  File "./canute_ui", line 4, in <module>
    main()
  File "/home/user/canute/canute-ui/ui/main.py", line 45, in main
    driver, config, args.fuzz_duration, loop))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/user/canute/canute-ui/ui/main.py", line 137, in run_async_timeout
    await run_async(driver, config, loop)
  File "/home/user/canute/canute-ui/ui/main.py", line 145, in run_async
    state = await initial_state.read(media_dir)
  File "/home/user/canute/canute-ui/ui/initial_state.py", line 127, in read
    user_state = await read_user_state(path)
  File "/home/user/canute/canute-ui/ui/initial_state.py", line 109, in read_user_state
    t = toml.load(toml_file)
  File "/usr/lib/python3/dist-packages/toml.py", line 30, in load
    return loads(ffile.read(), _dict)
  File "/usr/lib/python3/dist-packages/toml.py", line 91, in loads
    raise Exception("Found invalid character in key name: '"+sl[i]+"'. Try quoting the key name.")
```

with state files appearing like:

```
current_page = 0
bookmarks = []
,]
```

Gut feeling: fuzzing can generate large numbers of state changes very quickly, and there can be correspondingly large numbers of outstanding state write tasks.  This smells like a race between state writes.

**Comment by pachpict** [comment]
Marking as first-consumer-update on assumption there aren't m/any real-world cases likely. If assumption may be wrong please change to first-consumer-release milestone.
